FROM --platform=$TARGETPLATFORM alpine

RUN --mount=type=bind,from=khs1994/s6:2.0.0.1,source=/,target=/tmp/s6 \
    set -x \
    && tar -zxvf /tmp/s6/s6-overlay.tar.gz -C / \
    && ln -s /init /s6-init

RUN set -x ; uname -a ; s6-svscanctl --help

ENTRYPOINT ["/s6-init"]
