on: push

name: ci

jobs:
  build-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
      - uses: docker-practice/actions-setup-docker@master
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          set -x
          docker buildx build -t khs1994/s6 \
          --platform=linux/arm64,linux/arm/v7,linux/amd64 \
          --push \
          .
      - run: docker run --rm ubuntu   sh -cx "ls -la / ; if [ -h /bin ];then echo 1;fi"
      - run: docker run --rm centos:7 sh -cx "ls -la / ; if [ -h /bin ];then echo 1;fi"
      - run: docker run --rm centos:8 sh -cx "ls -la / ; if [ -h /bin ];then echo 1;fi"
      - run: docker run --rm centos   sh -cx "ls -la / ; if [ -h /bin ];then echo 1;fi"
      - run: docker run --rm fedora   sh -cx "ls -la / ; if [ -h /bin ];then echo 1;fi"

      - run: docker run --rm alpine   sh -cx "ls -la / ; if [ -h /bin ];then echo 1;fi"
      - run: docker run --rm debian   sh -cx "ls -la / ; if [ -h /bin ];then echo 1;fi"
      - run: docker image ls
      - run: |
          set -x
          docker buildx build -t test \
          --platform=linux/arm64,linux/arm/v7,linux/amd64 \
          -f Dockerfile.alpine \
          tests

          docker buildx build -t test \
          --platform=linux/arm64,linux/arm/v7,linux/amd64 \
          -f Dockerfile.ubuntu \
          tests

          docker buildx build -t test \
          --platform=linux/arm64,linux/arm/v7,linux/amd64 \
          -f Dockerfile.centos \
          tests
